version: '3.10.4'
services:

  dashboard:
    build: 
      context: ./
    container_name: ${COMPOSE_PROJECT_NAME}_dashboard
    hostname: ${COMPOSE_PROJECT_NAME}_dashboard
    restart: always
    ports:
      - 5040:80
    networks:
      - network 
    

      
networks:
  network:
    driver: bridge
